# Generated by Django 4.0 on 2022-03-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='router_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sapid', models.CharField(max_length=18)),
                ('Hostname', models.CharField(max_length=14)),
                ('Loopback', models.GenericIPAddressField()),
                ('Macaddress', models.CharField(max_length=17)),
            ],
            options={
                'db_table': 'router_details',
            },
        ),
    ]
