# Generated by Django 4.0 on 2022-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentproject', '0002_alter_router_details_sapid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router_details',
            name='Sapid',
            field=models.IntegerField(),
        ),
    ]
